### ISSUE TITLE
你好有相应的论文可供参考吗

### ISSUE THREAD

**Issue by TaylorWPY** [SangYuhiter/Knowledge-Map-and-Question-Answer#1]
你好有相应的论文可供参考吗，还有文件里面 大学学科(百度百科网页源码) 这个文件是什么呢

**Comment by SangYuhiter** [comment]
抱歉，你指的论文是毕设论文吗？这个还没有完成。大学学科（百度百科网页源码）是我在抓取中国大学的专业学科设置信息时，因为无法直接从代码中直接访问获取全部的源码（比如原网页中有点击查看更多的按钮），所以直接选择查看源代码，复制下来再进行解析。

**Comment by zouhuan** [comment]
你好，请问在question_type_predict_model.pre_load_fastText_model()里你的model_w2_e24是指什么呢，你是如何加载成功的呀

**Comment by SangYuhiter** [comment]
[upload commit](https://github.com/SangYuhiter/Knowledge-Map-and-Question-Answer/commit/045a6e9ff1e065c448148d8e7cd09d95ea24c750)
reference this change, already upload  the document.

**Comment by SangYuhiter** [comment]
find document in Knowledge-Map-and-Question-Answer/Document
