### ISSUE TITLE
你好，请问源码的模型model_w2_e24是指

### ISSUE THREAD

**Issue by zouhuan** [SangYuhiter/Knowledge-Map-and-Question-Answer#2]
你好，请问在question_type_predict_model.pre_load_fastText_model()里你的model_w2_e24是指什么呢，你是如何加载成功的呀

**Comment by SangYuhiter** [comment]
自己训练的分类模型，有点大无法上传，可以使用另一个项目里的训练方法进行训练https://github.com/SangYuhiter/Admission-Consult-fastText-Classifier
有问题可以加这个qq(1971506195),有时间尽力解答

**Comment by lxs-arch** [comment]
请问这个问题您解决了吗

**Comment by lxs-arch** [comment]
我的运行的时候有这个报错ValueError: model_w2_e24 cannot be opened for loading!，该怎么处理啊

**Comment by SangYuhiter** [comment]
[reference this commit](https://github.com/SangYuhiter/Knowledge-Map-and-Question-Answer/commit/b2b040565bb4e04b3ff6f1872437bb463c56fa59)
already update in this commit
